### ISSUE TITLE
Project Management Task checklist

### ISSUE THREAD

**Issue by JulianConneely** [JulianConneely/Programming-and-Scripting-Project--Spring-2018#1]
- [x] Research background information about the data set and write a summary about
it
- [x] Keep a list of references you used in completing the project
- [x] Download the data set and write some Python code to investigate it
- [x] Summarise the data set using a Py script, e.g. calculating the maximum, minimum and
mean of each column of the data set
- [x] Write a summary of my investigations
- [x] Include supporting tables and graphics as necessary

**Comment by JulianConneely** [comment]
WIP

**Comment by JulianConneely** [comment]
Browsing Github from mobile device
